name: Commitlint

on: [pull_request]

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: github.actor != 'dependabot[bot]'
    steps:
     - name: Checkout
       uses: actions/checkout@v7
       with:
         fetch-depth: 0
     - name: Commitlint
       uses: wagoid/commitlint-github-action@v6
